### ISSUE TITLE
Could not pass event InventoryClickEvent to GlobalMarket v2.0.0.20

### ISSUE THREAD

**Issue by LittleNightmare** [Dasfaust/GlobalMarket#104]
I can creat a list, but can not buy other one
`[11:28:44] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GlobalMarket v2.0.0.20
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[kuniu.jar:git-Spigot-b3c0272-7723b90]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[kuniu.jar:git-Spigot-b3c0272-7723b90]
    at me.Incomprehendable.WorldPlugins.FakePluginManager.fireEvent(FakePluginManager.java:138) [PerWorldPluginsCB%201.7.2-R0.2.jar:?]
    at me.Incomprehendable.WorldPlugins.FakePluginManager.callEvent(FakePluginManager.java:124) [PerWorldPluginsCB%201.7.2-R0.2.jar:?]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1603) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_95]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_95]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) [kuniu.jar:git-Spigot-b3c0272-7723b90]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_95]
Caused by: java.lang.NoSuchMethodError: net.milkbowl.vault.economy.Economy.has(Lorg/bukkit/OfflinePlayer;D)Z
    at me.dasfaust.gm.trade.ListingsHelper.buy(ListingsHelper.java:21) ~[?:?]
    at me.dasfaust.gm.trade.MarketListing.onClick(MarketListing.java:114) ~[?:?]
    at me.dasfaust.gm.MenuHandler.onClick(MenuHandler.java:161) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor167.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_95]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_95]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[kuniu.jar:git-Spigot-b3c0272-7723b90]
    ... 15 more`

**Comment by Dasfaust** [comment]
Do you have Vault installed? If so, which version?
