### ISSUE TITLE
Error when issued command /market

### ISSUE THREAD

**Issue by k-jiang** [Dasfaust/GlobalMarket#129]
```
[22:22:54] [Server thread/INFO]: k_jiang issued server command: /market
[22:22:54] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'market' in me.dasfaust.gm.command.CommandHandler$1(market)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.dasfaust.gm.menus.Menus$1.getTitle(Menus.java:41) ~[?:?]
	at me.dasfaust.gm.menus.MarketViewer.open(MarketViewer.java:88) ~[?:?]
	at me.dasfaust.gm.MenuHandler.initViewer(MenuHandler.java:53) ~[?:?]
	at me.dasfaust.gm.command.CommandHandler$1.execute(CommandHandler.java:69) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-e2a288c]
	... 14 more
```

Tested on Spigot 1.11.2 build 1129, with the latest dev build on branch 2.0.X (see #127 ).

If you fixed it I can test it for you. Just reply below  : )

**Comment by Dasfaust** [comment]
Looks related to #127 - may try building with the latest commits. My build server is down at the moment, had a security breach and I ended up nuking it from orbit! I'll have another service up soon.

**Comment by k-jiang** [comment]
I just tried the build with the latest commits. The same error occurs.
