### ISSUE TITLE
not support ProtocolLib 4.2.1 ? Please update

### ISSUE THREAD

**Issue by jomjonejame** [Dasfaust/GlobalMarket#138]
MC 1.8.8
GlobalMarket 2.0.0.28 Beta
ProtocolLib 4.2.1
Vault 1.5.6-b49

> [01:05:10] [Server thread/INFO]: [GlobalMarket] Enabling GlobalMarket v2.0.0.28
[01:05:10] [Server thread/ERROR]: Error occurred while enabling GlobalMarket v2.0.0.28 (Is it up to date?)
java.lang.NoSuchMethodError: com.comphenix.protocol.utility.MinecraftReflection.getBukkitItemStack(Lorg/bukkit/inventory/ItemStack;)Lorg/bukkit/inventory/ItemStack;
	at me.dasfaust.gm.trade.WrappedStack.<init>(WrappedStack.java:31) ~[?:?]
	at me.dasfaust.gm.config.Config.load(Config.java:222) ~[?:?]
	at me.dasfaust.gm.Core.onEnable(Core.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by Dasfaust** [comment]
I am closing this issue as `wontfix`, as this repository is going to be archived. You are welcome to fork and republish the project, if you wish. I know this issue is very old, sorry for the ping!
