### ISSUE TITLE
[Question] Does this work on 1.7.10 Cauldron modded servers?

### ISSUE THREAD

**Issue by koalalord9999** [Dasfaust/GlobalMarket#34]
So, I downloaded v1.3.0_7 and put into my plugins folder, launched server, and no folder was created for the plugin; in-game I can't type /market either. I was wondering if there is any specific way of installing Global Market onto a cauldron server. If there is, can you tell me? :) thanks in advance.

(Also, I'm using that marketforge or something that adds NBT data adaptability in the mods folder for the server.)

**Comment by Dasfaust** [comment]
Yes, it's compatible. Look for an error at startup. GlobalMarket*.jar goes into the plugins folder, and MarketCompanion*.jar goes into the mods folder.

**Comment by koalalord9999** [comment]
Thing is, it looks liek its just skipping the .jar when its loading up - doesn't give any errors :L

**Comment by koalalord9999** [comment]
Oh wait, here ya go..
[09:17:51] [Server thread/ERROR] [Minecraft/]: Could not load 'plugins/GlobalMarket.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:196) ~[JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_65]
Caused by: java.util.zip.ZipException: invalid END header (bad central directory offset)
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.7.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:215) ~[?:1.7.0_65]
	at java.util.zip.ZipFile.<init>(ZipFile.java:145) ~[?:1.7.0_65]
	at java.util.jar.JarFile.<init>(JarFile.java:154) ~[?:1.7.0_65]
	at java.util.jar.JarFile.<init>(JarFile.java:118) ~[?:1.7.0_65]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:184) ~[JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1231.04.209]
	... 10 more

**Comment by Dasfaust** [comment]
"java.util.zip.ZipException: invalid END header", sounds like you have a bad jar file, try re-downloading it.

**Comment by koalalord9999** [comment]
Ok - I'll use the one you just posted a few minutes ago xD

**Comment by Dasfaust** [comment]
Whoops, didn't mean to close. Your jar file is getting corrupted somewhere along the line. Are you uploading it via FTP? If you have SSH access try using wget. Any 1.7.10 Cauldron builds should work.

**Comment by GunnerHQ** [comment]
Hi. I've looked for an update of the GlobalMarket for 1.7.10. can you give a link? I couldn't find anything... I realy like the plugin but dunno how to get it for 1.7.10... sry if i bother...

**Comment by madtomic** [comment]
Latest build
http://build.survivorserver.com/job/GlobalMarket/lastSuccessfulBuild/artifact/build/libs/GlobalMarket-1.3.0-8.jar

This build should work on 1.7.10

**Comment by koalalord9999** [comment]
Dasfaust - I am uploading through Filezilla. I've noticed that it also corrupts player data when I try to NBT edit it. I dunno why it doesn't work :l

**Comment by Dasfaust** [comment]
Maybe try WinSCP? http://winscp.net/eng/download.php - going to close this as there's nothing I can really do, hope you can get it worked out.

**Comment by koalalord9999** [comment]
I don't mean this to keep getting opened - if this even goes through, just close it again. I finally figured out the problem. I have been uploading via ASCII and it appears when I upload the .jar as a Bianary it actually worked! So I want to thank you for linking the winscp, without that link I would have never even of thought of doing the google search that I did. So, thank you again :)
