### ISSUE TITLE
Search - Errors

### ISSUE THREAD

**Issue by madtomic** [Dasfaust/GlobalMarket#41]
This occurs when I try to search by dropping a diamond_sword onto the search map in market listing. The server crashes after this. I'm using the GlobalMarket v1.3.0-9

[16:13:18 WARN]: Failed to handle packet for /127.0.0.1:50834
java.lang.IndexOutOfBoundsException: Index: 47, Size: 45
        at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_25]
        at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_25]
        at net.minecraft.server.v1_7_R3.Container.getSlot(Container.java:105) ~[
spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java
:1471) ~[spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PacketPlayInWindowClick.a(SourceFile:32)
 ~[spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.PacketPlayInWindowClick.handle(SourceFil
e:10) ~[spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:184
) ~[spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.ServerConnection.c(ServerConnection.java
:81) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:7
31) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:2
84) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:5
84) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java
:490) [spigot1543.jar:git-Spigot-1543]
        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:6
28) [spigot1543.jar:git-Spigot-1543]

**Comment by madtomic** [comment]
It also give an Internal server error.
