### ISSUE TITLE
NPE on InventoryClickEvent

### ISSUE THREAD

**Issue by rlf** [Dasfaust/GlobalMarket#51]
```
[01:00:17] [Server thread/ERROR]: Could not pass event InventoryClickEvent to GlobalMarket v1.3.0-11
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:1588) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:31) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.PacketPlayInWindowClick.a(SourceFile:9) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0]
    at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-c46583f-e6f9fd4]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0]
Caused by: java.lang.NullPointerException
...
[01:00:55] [Server thread/WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 15 (raw: 15) in interface Listings, should have an ID of 31.
[01:00:55] [Server thread/WARN]: [GlobalMarket] Null IMarketItem in InventoryClickEvent with position 14 (raw: 14) in interface Listings, should have an ID of 31.
```

**Comment by rlf** [comment]
Running:
```
[INFO] This server is running CraftBukkit version git-Spigot-c46583f-e6f9fd4 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

9:38:44 AM CONSOLE: [INFO] GlobalMarket version 1.3.0-11

9:39:06 AM CONSOLE: [INFO] Vault version 1.5.0-b28
9:39:06 AM CONSOLE: [INFO] Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
9:39:06 AM CONSOLE: [INFO] Website: http://dev.bukkit.org/server-mods/vault/
9:39:06 AM CONSOLE: [INFO] Authors: cereal, Sleaker and mung3r
```

**Comment by rlf** [comment]
More along the same lines:
```
[14:05:29] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to GlobalMarket v1.3.0-11
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0]
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source) [?:1.7.0]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0]
Caused by: java.lang.NullPointerException
	at com.survivorserver.GlobalMarket.MailInterface.prepareItem(MailInterface.java:125) ~[?:?]
	at com.survivorserver.GlobalMarket.InterfaceHandler.refreshInterface(InterfaceHandler.java:260) ~[?:?]
	at com.survivorserver.GlobalMarket.InterfaceHandler.openInterface(InterfaceHandler.java:166) ~[?:?]
	at com.survivorserver.GlobalMarket.Market.onRightClick(Market.java:738) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-d0d1d87-bc03b6f]
	... 17 more
```

**Comment by rlf** [comment]
https://github.com/rlf/uSkyBlock/commit/ce16d59b4f4b74157a64568bf8e77e431c3a5eac

**Comment by rlf** [comment]
My `config.yml`.

Seems to be caused by multi-world support (or 1.8 items - not sure).
http://pastebin.com/aBVxaWAv
