### ISSUE TITLE
Items Turning into Transaction Logs

### ISSUE THREAD

**Issue by ghost** [Dasfaust/GlobalMarket#57]
I'm not really sure why this is happening. It's a fresh server we've just opened and some items are turning into transaction logs again. I'm using SQLite. There were some permission errors at first and it couldn't save to DB, but this was resolved. I'm not sure what else could cause this. I'm using MarketCompanion. I did also notice this error pop up in console, although I'm not sure if it's related:

```
[14:43:50 INFO]: [GlobalMarket] Error while building queued statement:
[14:43:50 WARN]: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_7_R4.inventory.CraftItemStack cannot be cast to me.dasfaust.GlobalMarket.WrappedItemStack
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.Lib.Cauldron.CauldronHelper.serialize(CauldronHelper.java:73)
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.MarketStorage.itemStackToString(MarketStorage.java:418)
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.SQL.MarketStatement.setItemStack(MarketStatement.java:73)
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.SQL.QueuedStatement.buildStatement(QueuedStatement.java:38)
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[14:43:50 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[14:43:50 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:43:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:43:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:43:50 WARN]:        at java.lang.Thread.run(Thread.java:745)
[14:43:50 ERROR]: [GlobalMarket] Error while processing DB queue:
[14:43:50 WARN]: java.lang.NullPointerException
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[14:43:50 WARN]:        at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[14:43:50 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[14:43:50 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[14:43:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[14:43:50 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[14:43:50 WARN]:        at java.lang.Thread.run(Thread.java:745)

```

Any help would be appreciated.

Thank you!

**Comment by Nentify** [comment]
Actually, would MarketCompanion cause this? I notice the log mentions that the plugin itself has Cauldron support. Do I need to use MarketCompanion?

**Comment by Dasfaust** [comment]
I doubt MarketCompanion would cause it. You do need it to save all NBT data from modded items. I haven't found the exact cause of the transaction log issue, so it may be best to [update to the 2.0.0 beta](https://github.com/Dasfaust/GlobalMarket/tree/2.0.X), it's still pretty incomplete but should be pretty stable. 2.0.0 has much better handling of NBT data but requires ProtocolLib. For Cauldron 1.7.10, the best ProtocolLib version to use is [3.4.0 from the BukkitDev page](http://dev.bukkit.org/bukkit-plugins/protocollib/files/32-protocol-lib-3-4-0/).

**Comment by Nentify** [comment]
I've been using 'ProtocolLib-Cauldron-3.4.1-SNAPSHOT.jar' from the Jenkins repo. I may look at 2.0.0. I looked at it before but stalls and searching were quite useful. I'll try without MarketCompanion for now... The old market server we had had it removed accidentally I think, and we never had issues with NBT data or transaction logs it seems. 2.0.0 does look really nice though from what I'm seen on GH/tickets and trying it out in-game. Thanks for all your work!

**Comment by Nentify** [comment]
With 2.X is it recommended to increase the save interval? I can imagine items disappearing if users put items into the market too close to a reset.

**Comment by Nentify** [comment]
Seems items, at least with JSON, aren't saving at all either. Restarting the server empties the market and there is no data in the json file.

**Comment by Dasfaust** [comment]
Use JSON unless you want to share data between multiple servers. Stalls and commands are coming, it'll probably be what I do next.

Save interval would only make a difference if the server crashes, as the plugin will do a save when the server stops normally.

Are you using Linux? Try chmod 777 -R on the GlobalMarket folder, or make sure the user running Minecraft owns the folder. But I guess it wouldn't create the file if that wasn't the case. What other plugins are you running?

**Comment by Nentify** [comment]
http://i.nentify.me/3ua4LT9x.png

**Comment by Dasfaust** [comment]
Should be fixed in build 10. Thanks for the details. The shading technique I'm using wasn't including all Gson files, going to need to find a better solution.

**Comment by Nentify** [comment]
Build 10 seems to be working, thanks! :)

**Comment by Nentify** [comment]
Is there information about permissions/commands anywhere? Thanks! :)

**Comment by Nentify** [comment]
If there's multiple stacks of an item in the market, purchasing the item reducing the price of the item by the fee amount I think...

http://i.nentify.me/byyAO1Rm.png
http://i.nentify.me/1gzWVVtu.png

`listings_cut_amount: 0.05`

**Comment by Dasfaust** [comment]
I guess there isn't, haha. I'll add a wiki entry soon. Currently, there is two permission nodes: globalmarket.use, which allows players to open the GUI and globalmarket.admin, which allows players to cancel other sellers' listings. The only command is /market, which opens the GUI. It's very bare-bones, fleshing all of that out is next on the to-do list.

**Comment by Dasfaust** [comment]
Didn't see your messages until I went to GitHub, weird. The expire time is just a number I picked of no real value, it's in hours. Something like 48-72 would work better. 

About price dropping, it's something I fixed awhile ago but seems I didn't commit to GitHub, whoops. Haha, should be fixed in build 11.

There is an option in the config to disable all of the debug. And no worries about the questions, glad to have feedback.

**Comment by Nentify** [comment]
Thanks!

The debug I pasted above shows despite the config setting debug to false

**Comment by Dasfaust** [comment]
Fixed in build 12.

**Comment by Nentify** [comment]
Thanks! Works perfectly. :)

Still 1 question - Will there be an easier way to add items to the market listings? The only issue some players have atm is setting the price/atm is quite tedious/annoying compared to GlobalMarket 1 where you could just enter a price, especially considering you're limited with the 1-9 keys.

**Comment by Dasfaust** [comment]
Yes, I will be doing commands. Probably config options for how much each button increments in the GUI, too, now that I think about it. Can't say when, but I'll have some extra free time in the next few days, so maybe then.

**Comment by Nentify** [comment]
That sounds great. :) Commands or having like 1 = 1, 2 = 5, 3 = 10, 4 = 50. 5 = 100, 6 = 500, 7 = 1000, 8 = 5000, 9 = 10000 or something would be great.

**Comment by Nentify** [comment]
Do stock slots groups work?

I have

```
stock_slots_groups:
- premium: 18
```

but users with premium as their secondary group still only have the default number of slots.

**Comment by Dasfaust** [comment]
They aren't implemented yet.
