### ISSUE TITLE
Restarting server console error (some items in market are gone)

### ISSUE THREAD

**Issue by Sikatsu** [Dasfaust/GlobalMarket#65]
When i restart my server i recieve an error and the items of people in the market are gone. The same happens when i want to remove an item from the market.

[17-09 08:53:46 ] [Server] WARN java.sql.SQLException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:383)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:387)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.execute(DB.java:342)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.executeUpdate(DB.java:363)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17-09 08:53:46 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.MarketStatement.execute(MarketStatement.java:97)
[17-09 08:53:46 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[17-09 08:53:46 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[17-09 08:53:46 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[17-09 08:53:46 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17-09 08:53:46 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[17-09 08:53:46 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[17-09 08:53:46 ] [Server] WARN at java.lang.Thread.run(Thread.java:744)
[17-09 08:53:46 ] [Server] [Informatie] An exception occurred while executing an SQL statement:
[17-09 08:53:46 ] [Server] WARN java.sql.SQLException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:383)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:387)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.execute(DB.java:342)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.DB.executeUpdate(DB.java:363)
[17-09 08:53:46 ] [Server] WARN at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17-09 08:53:46 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.MarketStatement.execute(MarketStatement.java:97)
[17-09 08:53:46 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[17-09 08:53:46 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[17-09 08:53:46 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[17-09 08:53:46 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17-09 08:53:46 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[17-09 08:53:46 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[17-09 08:53:46 ] [Server] WARN at java.lang.Thread.run(Thread.java:744)
[17-09 08:53:47 ] [Server] Skipped 30 lines due to rate limit (30/s)
[17-09 08:53:47 ] [Server] [Informatie] Error removing listing id 331
[17-09 08:53:47 ] [Server] WARN java.sql.SQLException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:383)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:387)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.execute(DB.java:342)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.executeUpdate(DB.java:363)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17-09 08:53:47 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.MarketStatement.execute(MarketStatement.java:97)
[17-09 08:53:47 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[17-09 08:53:47 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[17-09 08:53:47 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[17-09 08:53:47 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17-09 08:53:47 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[17-09 08:53:47 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[17-09 08:53:47 ] [Server] WARN at java.lang.Thread.run(Thread.java:744)
[17-09 08:53:47 ] [Server] [Informatie] An exception occurred while executing an SQL statement:
[17-09 08:53:47 ] [Server] WARN java.sql.SQLException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:383)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:387)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.execute(DB.java:342)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.DB.executeUpdate(DB.java:363)
[17-09 08:53:47 ] [Server] WARN at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17-09 08:53:47 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.MarketStatement.execute(MarketStatement.java:97)
[17-09 08:53:47 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[17-09 08:53:47 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[17-09 08:53:47 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[17-09 08:53:47 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17-09 08:53:47 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[17-09 08:53:47 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[17-09 08:53:47 ] [Server] WARN at java.lang.Thread.run(Thread.java:744)
[17-09 08:53:49 ] [Server] Skipped 60 lines due to rate limit (30/s)
[17-09 08:53:49 ] [Server] [Informatie] Error removing listing id 312
[17-09 08:53:49 ] [Server] WARN java.sql.SQLException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:383)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:387)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.execute(DB.java:342)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.executeUpdate(DB.java:363)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17-09 08:53:49 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.MarketStatement.execute(MarketStatement.java:97)
[17-09 08:53:49 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[17-09 08:53:49 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase$1.run(AsyncDatabase.java:37)
[17-09 08:53:49 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[17-09 08:53:49 ] [Server] WARN at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[17-09 08:53:49 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[17-09 08:53:49 ] [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[17-09 08:53:49 ] [Server] WARN at java.lang.Thread.run(Thread.java:744)
[17-09 08:53:49 ] [Server] [Informatie] An exception occurred while executing an SQL statement:
[17-09 08:53:49 ] [Server] WARN java.sql.SQLException: [SQLITE_CORRUPT] The database disk image is malformed (database disk image is malformed)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:383)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.newSQLException(DB.java:387)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.execute(DB.java:342)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.DB.executeUpdate(DB.java:363)
[17-09 08:53:49 ] [Server] WARN at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
[17-09 08:53:49 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.MarketStatement.execute(MarketStatement.java:97)
[17-09 08:53:49 ] [Server] WARN at com.survivorserver.GlobalMarket.SQL.AsyncDatabase.processQueue(AsyncDatabase.java:67)
[17-09 08:53:49 ] [

**Comment by Dasfaust** [comment]
I realize I'm a month late, but it sounds like bad write permissions or a full hard drive. Nothing I can fix on my end.
