### ISSUE TITLE
Error On /market Command MC1.7.10 GM 2.0.0.21

### ISSUE THREAD

**Issue by Time6628** [Dasfaust/GlobalMarket#71]
Getting this error with global market on Cauldron 1.7.10 with GlobalMarket 2.0.0.21
```
[15:59:15] [Server thread/INFO]: Kraise_ issued server command: /market
[15:59:15] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'market' in me.dasfaust.gm.command.CommandHandler$1(market)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-1566.UNOFFICIAL]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1566.UNOFFICIAL]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Item 115 doesn't exist
	at me.dasfaust.gm.storage.abs.StorageHandler.get(StorageHandler.java:115) ~[?:?]
	at me.dasfaust.gm.storage.abs.MarketObject.getItemStack(MarketObject.java:59) ~[?:?]
	at me.dasfaust.gm.menus.MarketViewer.buildMenu(MarketViewer.java:107) ~[?:?]
	at me.dasfaust.gm.menus.MarketViewer.open(MarketViewer.java:79) ~[?:?]
	at me.dasfaust.gm.MenuHandler.initViewer(MenuHandler.java:57) ~[?:?]
	at me.dasfaust.gm.command.CommandHandler$1.execute(CommandHandler.java:49) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1566.UNOFFICIAL]
	... 12 more
```

**Comment by Time6628** [comment]
Nevermind. :cat:
