### ISSUE TITLE
1.9 Loads - But errors - no in game response.

### ISSUE THREAD

**Issue by Snoogles** [Dasfaust/GlobalMarket#85]
I can not get a 1.9 version of global market to work. And even now if i downgrade it wont load properly. I have tried versions 2.0.0.20, 23, 27,28. I am using spigot version 23e921f-8b69bdd. The 1.8 version do not work either with these versions of spigot. 

[14:37:54] [Server thread/ERROR]: Error occurred while enabling GlobalMarket v2.0.0.28 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/utility/MinecraftReflection
	at me.dasfaust.gm.trade.WrappedStack.<init>(WrappedStack.java:31) ~[?:?]
	at me.dasfaust.gm.config.Config.load(Config.java:222) ~[?:?]
	at me.dasfaust.gm.Core.onEnable(Core.java:43) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_21]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.utility.MinecraftReflection
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_21]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_21]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_21]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_21]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-23e921f-8b69bdd]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423) ~[?:1.7.0_21]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356) ~[?:1.7.0_21]
	... 14 more

**Comment by Dasfaust** [comment]
Looks like you need to install ProtocolLib.
